### ISSUE TITLE
find package problem

### ISSUE THREAD

**Issue by ssafaei** [hsorby/OpenCMISS-FunctionalTests#1]
I added burgers_static example to the database and tested two of them together (with uniaxial) and  and it didn't work. The issue was:

-- Looking for OpenCMISS-Iron ... Success
CMake Error at /home/ssaf006/opencmiss/install/opencmisslibs-config.cmake:106 (add_library):
  add_library cannot create target "opencmisslibs" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "/home/ssaf006/Downloads/functional_tests-build/tests/burgers_static".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  finiteelasticity_uniaxialextension/CMakeLists.txt:24 (find_package)

-- Looking for OpenCMISS-Iron ...
-- FindBLAS wrapper: System search enabled

Also after removing uniaxial, there was another issue with file structure in burgers_static.
I think it needs to be modified to match the file structure that we agreed on for burgers.

-- Configuring done
CMake Error at CMakeLists.txt:13 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:burgers_static>

  No target "burgers_static"

-- Generating done

**Comment by hsorby** [comment]
Ok I'll have to adjust things a bit.  I'll need to but some guards around the opencmisslibs-config.cmake possibly.  Might try and get this done tomorrow.

**Comment by hsorby** [comment]
I think this issue is now resolved with the latest version of the software.

**Comment by hsorby** [comment]
Closing this issue as it has been resolved with changes elsewhere.
