### ISSUE TITLE
Parallel tests

### ISSUE THREAD

**Issue by lorenzo-mechbau** [hsorby/OpenCMISS-FunctionalTests#17]
Using the functional testing framework with the "develop" repository, I get the following error at burgers_dynamic in OpenCMISS-Examples, causing the test to fail:

Solving problem...
At line 157 of file /data/homes/zanon/software/opencmiss/opencmiss/src/dependencies/lapack/BLAS/SRC/dgemv.f
Fortran runtime error: Actual string length is shorter than the declared one for dummy argument 'trans' (-49050405/1)

This failure randomly alternates with a passed test.

Other tests (cantilever, uniaxial extension) always pass.

**Comment by lorenzo-mechbau** [comment]
I cannot run parallel tests. The test fails just by setting in the description .cmake file

set(TEST_MULTI_PROCESS True)
set(TEST_NP 4)

I guess this is because to successfully run parallel code I need to use the command mpiexec.hydra?

**Comment by hsorby** [comment]
No it should identify that multi process is true and then use mpirun to execute the test.

**Comment by hsorby** [comment]
Those two lines are commented out? Just checking that that isn't the case when you try and run the tests in multi process mode.

**Comment by lorenzo-mechbau** [comment]
Sorry! Yes, when I was actually running the tests, there was no comment sign. Then, since it was unsuccessful, I added the comment.

On my computer (and the current mpich installation, which I should update...) I have to use the command mpiexec.hydra whenever I run in parallel, mpirun would not work.

Thanks!!

**Comment by lorenzo-mechbau** [comment]
The problem with the parallel tests was due to my mpi installation (standard mpich). The issue has been solved reinstalling mpich (or openmpi).

I moved the issue about the burgers_dynamic example (first post) to a different issue.
